{
 "title": "grafana_mysql_template",
 "description": "mysql and mariadb template",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "主机数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  value\nFROM hosts_number\nWHERE \n  name='complete_number'"
    }
   ]
  },
  {
   "title": "扫描结果",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  result\nFROM scan_result"
    }
   ]
  },
  {
   "title": "本次扫描日期",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  from_unixtime(current_scan_time,'%Y-%m-%d')\nFROM scan_result\nWHERE\n  id=1"
    }
   ]
  },
  {
   "title": "下次扫描日期",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  from_unixtime(next_scan_time,'%Y-%m-%d')\nFROM scan_result\nWHERE\n  id=1"
    }
   ]
  },
  {
   "title": "应用程序账号数量",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  name,value\nFROM number_of_application_accounts"
    }
   ]
  },
  {
   "title": "应用程序登录失败记录",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 11, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  attempt_failed as '失败次数', attempt_ip as '登录IP', from_unixtime(attempt_clock,'%Y-%m-%d') as '日期'\r\nFROM program_page_login_failed_times\r\nWHERE\r\n  attempt_failed != '0'\r\norder by attempt_clock "
    }
   ]
  },
  {
   "title": "系统密码上次修改时间",
   "type": "stat",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  from_unixtime(date_time,'%Y/%m/%d') as date_time, times\nFROM system_password_last_modified\norder by date_time desc"
    }
   ]
  },
  {
   "title": "操作系统账号数",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  value,sum(value)\nFROM number_of_accounts_scanned"
    }
   ]
  },
  {
   "title": "应用程序账号角色分类",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  name,value\nFROM program_user_roles"
    }
   ]
  },
  {
   "title": "应用程序账号数",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  value\nFROM number_of_accounts_scanned\n"
    }
   ]
  },
  {
   "title": "应用程序账号组成员排名",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  name, value\nFROM program_username_classification\norder by value desc"
    }
   ]
  }
 ]
}